# Generated by Django 5.2.11 on 2026-02-07 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modifiedDateTime', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=1024)),
                ('message', models.TextField(blank=True, null=True)),
                ('emails', models.TextField(help_text='Comma separated email addresses')),
                ('eventDateTime', models.DateTimeField()),
                ('startBeforeDays', models.PositiveIntegerField(blank=True, help_text='Days before event to start reminders (default = 2)', null=True)),
                ('intervalValue', models.PositiveIntegerField(help_text='Send reminder every X units')),
                ('intervalUnit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], max_length=10)),
                ('nextReminderDateTime', models.DateTimeField(blank=True, help_text='Next scheduled reminder time', null=True)),
                ('lastSentDate', models.DateField(blank=True, null=True)),
                ('sentCountToday', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('retryCount', models.PositiveIntegerField(default=0)),
                ('lastFailureDateTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event Reminder',
                'verbose_name_plural': 'Event Reminders',
                'ordering': ['eventDateTime'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modifiedDateTime', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartCardNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('identifier', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('utilityMarket', models.CharField(blank=True, choices=[('ELECTRICITY', 'Electricity'), ('GAS', 'Gas')], max_length=64, null=True)),
                ('tariff', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('SAFEGUARD_PAYG', 'Safeguard PAYG')], max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Meter Point',
                'verbose_name_plural': 'Meter Points',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modifiedDateTime', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('content', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, related_name='journalEntryTags', to='core.tag')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-modifiedDateTime'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('identifier', models.CharField(choices=[('OFFICE', 'Office'), ('MISCELLANEOUS', 'Miscellaneous'), ('WIRE', 'Wire'), ('CABLE', 'Cable'), ('UNKNOWN', 'Unknown'), ('COMPUTER', 'Computer'), ('OTHER', 'Other'), ('TOOLS', 'Tools')], default='OTHER', max_length=16)),
                ('box', models.CharField(choices=[('NONE', 'None'), ('A3', 'A3'), ('MB1', 'MB1'), ('FLX1', 'FLX1'), ('FLX2', 'FLX2'), ('FLX3', 'FLX3'), ('FLX4', 'FLX4'), ('NLA1', 'NLA1'), ('NLA2', 'NLA2'), ('NLA3', 'NLA3'), ('NLA4', 'NLA4'), ('NLA6', 'NLA6'), ('NLA7', 'NLA7'), ('WORK', 'Work'), ('TODO', 'Todo')], default='FLX4', max_length=16)),
                ('isWorking', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='inventoryItemTags', to='core.tag')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
        migrations.CreateModel(
            name='CatPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(choices=[('AMAZON', 'Amazon'), ('EBAY', 'eBay'), ('BITIBA', 'Bitiba'), ('ZOOPLUS', 'Zooplus'), ('PETSHOP', 'PetShop'), ('TIKTOK', 'TikTok'), ('VETSHOP', 'VetShop'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('date', models.DateField()),
                ('brand', models.CharField(choices=[('PURINA_ONE', 'PurinaOne'), ('FELIX', 'Felix'), ('WHISKAS', 'Whiskas'), ('FRONTLINE', 'Frontline'), ('DRONTAL', 'Drontal'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('item', models.CharField(choices=[('FOOD', 'Food'), ('FLEA', 'Flea'), ('WORMER', 'Wormer'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('pouchPerBox', models.PositiveSmallIntegerField()),
                ('unitWeight', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tags', models.ManyToManyField(blank=True, related_name='catPurchasesTags', to='core.tag')),
            ],
            options={
                'verbose_name': 'Cat Purchases',
                'verbose_name_plural': 'Cat Purchases',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modifiedDateTime', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('breed', models.CharField(blank=True, max_length=1024, null=True)),
                ('colour', models.CharField(blank=True, max_length=1024, null=True)),
                ('microchip', models.CharField(blank=True, max_length=1024, null=True)),
                ('additionalData', models.TextField(blank=True, null=True)),
                ('dateOfBirth', models.DateField()),
                ('tags', models.ManyToManyField(blank=True, related_name='catTags', to='core.tag')),
            ],
            options={
                'verbose_name': 'Cat',
                'verbose_name_plural': 'Cats',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.goal')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('channel', models.CharField(blank=True, choices=[('APP', 'App'), ('ONLINE', 'Online'), ('OTHER', 'Other'), ('PEAK_SAVE', 'PeakSave'), ('PORTAL', 'Portal'), ('WARM_HOME_DISCOUNT', 'Warm Home Discount'), ('WEB', 'Web')], max_length=32, null=True)),
                ('topUpCode', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meterPoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energyPaymentMeterPoint', to='core.meterpoint')),
            ],
            options={
                'verbose_name': 'Energy Payment',
                'verbose_name_plural': 'Energy Payments',
                'ordering': ['-date', '-time'],
                'unique_together': {('date', 'time', 'channel', 'topUpCode', 'amount', 'meterPoint')},
            },
        ),
    ]
