# Generated by Django 5.2.11 on 2026-04-24 11:38

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='catpurchases',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='catpurchases',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='catpurchases',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='energypayment',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='energypayment',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='energypayment',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='goal',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='meterpoint',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meterpoint',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='meterpoint',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='property',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='tag',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, max_length=8),
        ),
        migrations.AddField(
            model_name='task',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
