# Generated by Django 5.2.11 on 2026-04-24 11:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cat_internalid_catpurchases_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='catpurchases',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='energypayment',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='eventreminder',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='meterpoint',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='internalId',
            field=models.CharField(default=core.models.generateExternalId, editable=False, max_length=8, unique=True),
        ),
    ]
